# Generated by Django 3.0.6 on 2020-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.CharField(max_length=200),
        ),
    ]
